apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:370849260309:certificate/0d6881c7-a274-4505-a37b-36a13769eb8a
    alb.ingress.kubernetes.io/group.name: ntt
    alb.ingress.kubernetes.io/healthcheck-path: /graphql
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
  name: saleor-k8s-{{.Values.environment}}-saleor-core-api
spec:
  ingressClassName: aws-load-balancer
  rules:
  - host: saleor-k8s-{{.Values.environment}}-saleor-core-api.hack.cloudnative.nttdatauk.cloud
    http:
      paths:
      - backend:
          service:
            name: saleor-k8s-{{.Values.environment}}-saleor-core-api
            port:
              number: 80
        path: /
        pathType: Prefix
